version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: bot
      prefix-development: bot
      include: scope
    groups:
      production-patch-minor:
        dependency-type: production
        update-types:
          - minor
          - patch
      production-major:
        dependency-type: production
        update-types:
          - major
      development-patch-minor:
        dependency-type: development
        update-types:
          - minor
          - patch
      development-major:
        dependency-type: development
        update-types:
          - major
